### ISSUE TITLE
Looking for the entry point

### ISSUE THREAD

**Issue by avidale** [RussianNLP/rusenteval#2]
Hi everyone!
Please help me to find the entry point to your code. I want to benchmark my own model, and I cannot find an obvious way to do it. Is there something like a script that I can feed my model to and run it on all tasks?

**Comment by vmkhlv** [comment]
@avidale hi

Here is an example of how to run the HugginFace m-BERT model on the *SentLen* and *SubjNumber* tasks using the supervised probing method (non-linear classifier). You may need to preliminarily upload your model to the HuggingFace hub.

If any questions left, don't hesitate to contact me on telegram @vmkhlv

```
from probing.arguments import ProbingArguments
from probing.experiment import Experiment


tasks = ["sent_len", "subj_number"]
# name of the HuggingFace model; you can adjust the code for your model
model = "bert-base-multilingual-cased"
args = ProbingArguments()

# args.clf == "logreg" or args.clf == "mlp" for linear/non-linear classification
args.clf = "mlp"

experiment = Experiment(tasks, model, args)
experiment.run()
```
